services:
  postgres:
    image: postgres:14
    container_name: appointment_system_db
    environment:
      POSTGRES_DB: appointment_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
